var express = require('express');
var router = express.Router();
const fs = require('fs')
const path = require('path')

// http://localhost:9000 is the URL generated by devServer
// configured in webpack
//localhost:9000
const getStaticAssetsPath = () =>
  process.env.NODE_ENV !== 'production' ? '' : ''

/* GET home page. */
router.get('/', function(req, res, next) {
  return res.sendFile(path.join(__dirname, '../../client/dist/index.html'))
  // // 
  // res.render('index', {
  //   title: 'Express',
  //   staticAssetsPath: getStaticAssetsPath()
  // });
});

router.get('/foo', function(req, res, next) {
  return res.send('foo')
});

module.exports = router;
